# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name attacker.test;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name attacker.test;

    ssl_certificate /etc/nginx/certs/local-cert.pem;
    ssl_certificate_key /etc/nginx/certs/local-key.pem;

    root /usr/share/nginx/html/attacker-site;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
