upstream banking_backend {
    server host.docker.internal:8000;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    server_name banking.test;
    return 301 https://$host$request_uri;
}

# The HTTPS Server
server {
    listen 443 ssl;
    server_name banking.test;

    # SSL Config
    ssl_certificate /etc/nginx/certs/local-cert.pem;
    ssl_certificate_key /etc/nginx/certs/local-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://banking_backend;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # CRITICAL: Tell FastAPI we are using HTTPS
        proxy_set_header X-Forwarded-Proto https;
    }
}
